name: Manual Trigger Workflow on Feature

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run build script
        run: echo "This workflow can be triggered manually."
